APP View/Models/ErrorViewModel.cs
namespace APP_View.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

APP View/Controllers/HomeController.cs
using APP_View.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace APP_View.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

APP View/Controllers/NhanVienController.cs
using APP_View.Controllers;
using AppData;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AppView.Controllers
{
    public class NhanVienController : Controller
    {
        private readonly ILogger<NhanVienController> _logger;

        public NhanVienController(ILogger<NhanVienController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddNhanVien()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddNhanVien(NhanVien nv)
        {
            string apiUrl = "https://localhost:7112/api/NhanVien/create";
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.PostAsJsonAsync(apiUrl, nv);// Lấy dữ liệu ra
            return RedirectToAction("GetAllNhanVien");
        }
        public async Task<IActionResult> GetAllNhanVien()
        {
            string apiUrl = "https://localhost:7112/api/NhanVien";
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.GetAsync(apiUrl);// Lấy dữ liệu ra
            //Lấy dữ liệu Json trả về từ Api được call dạng string
            string apiData = await response.Content.ReadAsStringAsync();
            //Lấy kqua trả về từ API
            // Đọc từ string Json vừa thu được sang List<T>
            var nhanviens = JsonConvert.DeserializeObject<List<NhanVien>>(apiData);
            return View(nhanviens);
        }

        [HttpGet]
        public async Task<IActionResult> DetailNhanVien(Guid id)
        {
            string apiUrl = "https://localhost:7112/api/NhanVien/" + id;
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.GetAsync(apiUrl);// Lấy dữ liệu ra
                                                             // Lấy dữ liệu Json trả về từ Api được call dạng string
            string apiData = await response.Content.ReadAsStringAsync();
            // Lấy kqua trả về từ API
            // Đọc từ string Json vừa thu được sang List<T>
            var nhanviens = JsonConvert.DeserializeObject<NhanVien>(apiData);
            return View(nhanviens);
        }
        [HttpGet]
        public async Task<IActionResult> EditNhanVien(Guid id)
        {
            string apiUrl = "https://localhost:7112/api/NhanVien/" + id;
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.GetAsync(apiUrl);// Lấy dữ liệu ra
                                                             // Lấy dữ liệu Json trả về từ Api được call dạng string
            string apiData = await response.Content.ReadAsStringAsync();
            // Lấy kqua trả về từ API
            // Đọc từ string Json vừa thu được sang List<T>
            var sanphams = JsonConvert.DeserializeObject<NhanVien>(apiData);
            return View(sanphams);

        }
        [HttpPost]
        public async Task<IActionResult> EditNhanVien(NhanVien nv)
        {
            string apiUrl = "https://localhost:7112/api/NhanVien/update";
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.PutAsJsonAsync(apiUrl, nv);// Lấy dữ liệu ra
                                                                       // Lấy dữ liệu Json trả về từ Api được call dạng string
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllNhanVien");
            }
            return View("EditNhanVien");
        }
        //[HttpDelete]
        public async Task<IActionResult> DeleteNhanVien(Guid id)
        {
            string apiUrl = "https://localhost:7112/api/NhanVien/delete/" + id;
            var httpClient = new HttpClient(); // tạo ra để callApi
            var response = await httpClient.GetAsync(apiUrl);// Lấy dữ liệu ra
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllNhanVien");
            }
            return View("Index");
        }
    }
}

APP View/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

APP View/Views/NhanVien/AddNhanVien.cshtml
@model AppData.NhanVien

@{
    ViewData["Title"] = "AddNhanVien";
}

<h1>AddNhanVien</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddNhanVien">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @* <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuoi" class="control-label"></label>
                <input asp-for="Tuoi" class="form-control" />
                <span asp-validation-for="Tuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control" />
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

APP View/Views/NhanVien/DetailNhanVien.cshtml
@model AppData.NhanVien

@{
    ViewData["Title"] = "DetailNhanVien";
}

<h1>DetailNhanVien</h1>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tuoi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tuoi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Luong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Luong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

APP View/Views/NhanVien/EditNhanVien.cshtml
@model AppData.NhanVien

@{
    ViewData["Title"] = "EditNhanVien";
}

<h1>EditNhanVien</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditNhanVien">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuoi" class="control-label"></label>
                <input asp-for="Tuoi" class="form-control" />
                <span asp-validation-for="Tuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Luong" class="control-label"></label>
                <input asp-for="Luong" class="form-control" />
                <span asp-validation-for="Luong" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

APP View/Views/NhanVien/GetAllNhanVien.cshtml
@model IEnumerable<AppData.NhanVien>

@{
    ViewData["Title"] = "GetAllNhanVien";
}

<h1>GetAllNhanVien</h1>

<p>
    <a asp-action="AddNhanVien">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tuoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Luong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tuoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Luong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                    @Html.ActionLink("Edit", "EditNhanVien", new { id=item.ID}) |
                    @Html.ActionLink("Details", "DetailNhanVien", new { id=item.ID }) |
                    @Html.ActionLink("Delete", "DeleteNhanVien", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

APP View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APP_View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APP_View.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APP_View</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="GetAllNhanVien">ShowAllNhanVien</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - APP_View - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>